---
title: "`r paste0('Your report from annoFuse - ', project_id)`"
author: "`r paste0('annoFuse happy_hour (v', utils::packageVersion('annoFuse'), ')')`"
date: "`r Sys.Date()`"

output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
    code_download: true
    number_sections: true
    df_print: kable
    theme: lumen
always_allow_html: yes
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE, 
  message = FALSE,
  error = TRUE
)
# knitr::opts_knit$set(
#   progress = FALSE, 
#   verbose = FALSE
# )
```


# Intro

```{r echo = TRUE}
out_annofuse
```

# Output table

Enhancing with buttons...

```{r}

# enhancing the content of the table

enhanced_annofuse_tbl <- annofuse_tbl
enhanced_annofuse_tbl$Gene1A <- .multilink(enhanced_annofuse_tbl$Gene1A)
enhanced_annofuse_tbl$Gene1B <- .multilink(enhanced_annofuse_tbl$Gene1B)

## would need to be made unique - and maybe keep frozen while scrolling the table
# rownames(enhanced_annofuse_tbl) <- enhanced_annofuse_tbl$FusionName
```

And rendering!

```{r}
DT::datatable(
  enhanced_annofuse_tbl,
  filter = "top",
  selection = "single",
  extensions = c("Buttons"),
  escape = FALSE,
  options = list(
    scrollX = TRUE,
    pageLength = 25,
    lengthMenu = c(5, 10, 25, 50, 100, nrow(enhanced_annofuse_tbl)),
    dom = "Bfrtip",
    buttons = list("copy", "print", list(
        extend = "collection",
        buttons = c("csv", "excel", "pdf"),
        text = "Download"
      )
    )
  )
)


```



# Session info {-}

```{r}
sessionInfo()
```

